/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void testRoll(){
        int [] testLength  = Library.roll(5);
        assertTrue("the lenght is 5",testLength.length == 5);
        for (int i =0;i<testLength.length;i++){
            assertTrue("item between 1 and 6",testLength[i]>=1 && testLength[i]<=6);
        }

    }
    @Test public  void  testGetAvg(){
        int [] arr  = {1,2,3,4};
        assertTrue("the avg is 2.5",Library.getAvg(arr) == 2.5);
    }

    @Test public  void  testContainDuplicate(){
        int [] arr  = {1,2,3,4,4};
        assertTrue("this array contains duplicates",Library.containsDuplicates(arr) == true);
    }
    @Test public void  testSmallArrayAvg(){
        int [][] arr  = {{1,1,1,1},{2,2,2,2},{3,3,3,3}};
        assertTrue("the lowest array avg is [1,1,1,1]",Library.smallArrayAvg(arr).equals(arr[0]));
    }
}
