/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant allward = new Restaurant("allward",5,"$");
        Review note = new Review("good","abdallah",4);
        System.out.println(note.toString());

        allward.addReview("is the best","malik",5);
        System.out.println(allward.toString());
        allward.addReview("not too good","mohammad",2);
        System.out.println(allward.toString());
        System.out.println();





    }
}