/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testResturentToString() {
        Restaurant r1 = new Restaurant("mac",5,2);
        System.out.println(r1.toString());
        String note = r1.toString();
        assertEquals("Restaurant name is mac rating in stars is : 5.0* price category: 2.0$",note);
    }
    @Test void testReviewToString() {
        Review r1 = new Review("bad","malik",2);
        System.out.println(r1.toString());
        String note = r1.toString();
        assertEquals("rating : bad Clint name: malik rating with stars is : 2",note);



    }

    @Test void testAssosaition() {
        Restaurant r1 = new Restaurant("bad", 5, 2);
        r1.addReview("good","mazen",5);
        r1.addReview("bad","majed",1);
//        String note =  r1.reviewList.toString();
//        System.out.println(note);
        r1.reviewList.toString();


//        assertEquals("this statement is from review class",note);
    }
    @Test void testAddReview(){
        Restaurant r1 = new Restaurant("mac",0,2);
        Review r2 = new Review("good","abd",4);

        r1.addReview("good","abd",4);
        String note =r1.toString();
        System.out.println(note);

        assertEquals("Restaurant name is mac rating in stars is : 2.0* price category: 2.0$",note);



    }


}
